export const SET_BREAK_LENGTH = "SET_BREAK_LENGTH";
export const SET_SESSION_LENGTH = "SET_SESSION_LENGTH";
export const RESET_TIMER = "RESET_TIMER";
export const TOGGLE_TIMER = "TOGGLE_TIMER";
export const TICK_TIMER = "TICK_TIMER";